services:
  bedrock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bedrock
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
    restart: unless-stopped

networks:
  bedrock:
