services:
  bedrock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bedrock
    ports:
      - "8888:8888"
    networks:
      - bedrock
    environment:
      DATABASE_URL: ${DATABASE_URL}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - bedrock
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

      


networks:
  bedrock:
  